# Generated by Django 5.2.3 on 2026-08-22 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cPlatformIO', '0002_dataflowstreamconfig_service_nullable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='algoinfer',
            name='Algo',
        ),
        migrations.RemoveField(
            model_name='algoinfer',
            name='ModelInfer',
        ),
        migrations.RemoveField(
            model_name='algoinfo',
            name='Model',
        ),
        migrations.RemoveField(
            model_name='modelcomparerow',
            name='Algo',
        ),
        migrations.RemoveField(
            model_name='dataflowbatchconfig',
            name='service',
        ),
        migrations.DeleteModel(
            name='DataFlowLogs',
        ),
        migrations.DeleteModel(
            name='DataflowRealtimeConfig',
        ),
        migrations.RemoveField(
            model_name='dataflowstreamconfig',
            name='service',
        ),
        migrations.RemoveField(
            model_name='dbpullinferencejob',
            name='Model',
        ),
        migrations.RemoveField(
            model_name='dbpullinferencelog',
            name='Job',
        ),
        migrations.RemoveField(
            model_name='inferenceresource',
            name='Application',
        ),
        migrations.RemoveField(
            model_name='inferenceresource',
            name='service',
        ),
        migrations.RemoveField(
            model_name='modelcomparerow',
            name='ModelCompare',
        ),
        migrations.RemoveField(
            model_name='modelinfer',
            name='Model',
        ),
        migrations.RemoveField(
            model_name='modelinfo',
            name='service',
        ),
        migrations.RemoveField(
            model_name='resourcerow',
            name='Model',
        ),
        migrations.RemoveField(
            model_name='reportinfo',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reportlog',
            name='report',
        ),
        migrations.RemoveField(
            model_name='resourcerow',
            name='service',
        ),
        migrations.AlterField(
            model_name='nodeevent',
            name='event_severity',
            field=models.CharField(choices=[('CRITICAL', 'CRITICAL'), ('HIGH', 'HIGH'), ('MEDIUM', 'MEDIUM'), ('LOW', 'LOW'), ('INFO', 'INFO')], max_length=100),
        ),
        migrations.AlterField(
            model_name='serviceevent',
            name='event_severity',
            field=models.CharField(choices=[('CRITICAL', 'CRITICAL'), ('HIGH', 'HIGH'), ('MEDIUM', 'MEDIUM'), ('LOW', 'LOW'), ('INFO', 'INFO')], max_length=100),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_role',
            field=models.CharField(choices=[('System_Admin', 'System_Admin'), ('Operational', 'Operational'), ('Developer', 'Developer'), ('Viewer', 'Viewer')], max_length=50),
        ),
        migrations.DeleteModel(
            name='AlgoInfer',
        ),
        migrations.DeleteModel(
            name='AlgoInfo',
        ),
        migrations.DeleteModel(
            name='DataflowBatchConfig',
        ),
        migrations.DeleteModel(
            name='DataflowStreamConfig',
        ),
        migrations.DeleteModel(
            name='DBPullInferenceJob',
        ),
        migrations.DeleteModel(
            name='DBPullInferenceLog',
        ),
        migrations.DeleteModel(
            name='InferenceResource',
        ),
        migrations.DeleteModel(
            name='ModelCompare',
        ),
        migrations.DeleteModel(
            name='ModelCompareRow',
        ),
        migrations.DeleteModel(
            name='ModelInfer',
        ),
        migrations.DeleteModel(
            name='ModelInfo',
        ),
        migrations.DeleteModel(
            name='ReportInfo',
        ),
        migrations.DeleteModel(
            name='ReportLog',
        ),
        migrations.DeleteModel(
            name='ResourceRow',
        ),
    ]
