apiVersion: v1
kind: Secret
metadata:
  name: docker-login-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsiYXV0aCI6ImFXdDBZWEpoT2tscmRHRnlZVUF6TWpFPSJ9fX0=
  password: SWt0YXJhQDMyMQ==


