# Service for iktara-cplatform-training
apiVersion: v1
kind: Service
metadata:
  name: iktara-cplatform-training-service
spec:
  selector:
    app: cplatform-iktara-training
  ports:
  - name: http
    port: 7002
    targetPort: 7002
    nodePort: 32000
  type: NodePort
