"""
Django settings for cPlatform project.

Generated by 'django-admin startproject' using Django 3.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
import sys
import yaml
from dotenv import load_dotenv

BASE_DIR = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(BASE_DIR))
sys.path.insert(0, str(BASE_DIR / "apps"))
sys.path.insert(0, str(BASE_DIR / "packages"))
sys.path.insert(0, str(BASE_DIR / "apps" / "platformops"))

temp_path = os.path.join(BASE_DIR, 'config')
NEW_BASE_DIR = BASE_DIR
sys.path.append(str(NEW_BASE_DIR))

ENV_FILE = os.environ.get('DJANGO_ENV_FILE', str(BASE_DIR / 'config' / 'local.env'))
if os.path.exists(ENV_FILE):
    load_dotenv(ENV_FILE)

from cPlatformIO.src.PlatformSetting import PlatformSettings

project_config_file = temp_path + '/projectConfig.yaml'
if os.path.exists(project_config_file):
    with open(project_config_file) as fh:
        projectConfig = yaml.load(fh, Loader=yaml.FullLoader) or {}
else:
    projectConfig = {}


def get_repository_path():
    deploy = PlatformSettings.deployment_type
    return BASE_DIR / PlatformSettings.repository_path


REPOSITORY_PATH = get_repository_path()
REPOSITORY_PATH.mkdir(parents=True, exist_ok=True)

SECRET_KEY = PlatformSettings.django_secret_key or 'django-insecure-platformops-core-secret-key-2026'
DEBUG = True

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'data', 'media')
IMG_URL = '/artifact/'
IMG_ROOT = str(REPOSITORY_PATH)

ALLOWED_HOSTS = ['*']

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_prometheus',
    'django_celery_beat',
    'gunicorn',
    'cPlatformIO',
]

MIDDLEWARE = [
    'cPlatform.middleware.ExceptionLoggingMiddleware',
    'django_prometheus.middleware.PrometheusBeforeMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'cPlatformIO.middleware.NoCacheMiddleware',
    'django_prometheus.middleware.PrometheusAfterMiddleware',
]

ROOT_URLCONF = 'cPlatform.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, "templates_new"),
            os.path.join(BASE_DIR, "templates"),
            os.path.join(BASE_DIR, "templates_new", "PlatformIO"),
            os.path.join(BASE_DIR, "templates", "PlatformIO"),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'libraries': {'my_templatetag': 'cPlatformIO.templatetags.auto_extras',}
        },
    },
]

WSGI_APPLICATION = 'cPlatform.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = PlatformSettings.time_zone

USE_I18N = True

USE_L10N = True

USE_TZ = True

'''
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


DATABASES = {
      'default': {
         'ENGINE': 'django.db.backends.postgresql_psycopg2',
         'NAME': cPlatformSettings.psql_database,
         'HOST': cPlatformSettings.psql_host,
         'PORT': cPlatformSettings.psql_port,
         'USER': cPlatformSettings.psql_username,
         'PASSWORD': cPlatformSettings.psql_password,
     }
 }
'''

DATABASES = {
    'default': {
        'ENGINE': os.environ.get('DJANGO_DB_ENGINE', 'django.db.backends.postgresql_psycopg2'),
        'NAME': os.environ.get('POSTGRES_DATABASE', 'postgres'),
        'USER': os.environ.get('POSTGRES_USER', 'postgres'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD', 'password'),
        'HOST': os.environ.get('POSTGRES_HOST', 'postgres'),
        'PORT': int(os.environ.get('POSTGRES_PORT', 5432)),
    }
}


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
    os.path.join(NEW_BASE_DIR, "CutilJS")
]
# Where static files will be collected
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

LOGIN_REDIRECT_URL = projectConfig.get('LOGIN_REDIRECT', '/PlatformIO/ClusterView/')
LOGIN_URL = 'login'
LOGOUT_REDIRECT_URL = 'login'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
EMAIL_HOST = PlatformSettings.mail_host
EMAIL_PORT = PlatformSettings.mail_port
EMAIL_HOST_USER = PlatformSettings.mail_username
EMAIL_HOST_PASSWORD = PlatformSettings.mail_password
SERVER_EMAIL = EMAIL_HOST_USER
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
DATA_UPLOAD_MAX_MEMORY_SIZE = 1024 * 1024 * 1024   # 50 MB, up from Django's 2.5 MB default
FILE_UPLOAD_MAX_MEMORY_SIZE = 1024 * 1024 * 1024
PASSWORD_RESET_TIMEOUT = 300

CSRF_TRUSTED_ORIGINS = [
    'https://iktaratech.co',
    'https://www.iktaratech.co',
]



